### ISSUE TITLE
Add this to the main nix distribution?

### ISSUE THREAD

**Issue by copumpkin** [madjar/nixbang#1]
This seems useful enough to warrant addition to the main nix distribution? @edolstra @rbvermaa?

**Comment by edolstra** [comment]
Too bad I didn't know about this, because I added similar functionality to nix-shell a while ago: NixOS/Nix@a957893b261a4438101c205e38fe8ce62b83a121

**Comment by madjar** [comment]
Great, that solves the question!

I'll add a not to the readme about that feature of nix-shell.

By the way, is `-i` short for `--command`?

**Comment by edolstra** [comment]
It's short for "interpreter". It's not quite the same as `--command` because it adds an `exec` and the script file name (and some ugly hack to support Perl scripts...).

**Comment by madjar** [comment]
I added a note to the readme in 6989ee1 to tell about this nix-shell feature, so I guess that resolves this issue.
